[build]
builder = "nixpacks"

[deploy]
startCommand = "node src/http-server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
  name = "web"

[services.variables]
  NODE_ENV = "production"
